In [1]:
import numpy as np

y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [2]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        # running for loop parallelly on 2 arrays
        total_error += abs(yp - yt)
    print("Total error is: ",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is: ",mae)
    return mae

In [3]:
mae(y_predicted, y_true)

Total error is:  2.5
Mean absolute error is:  0.5


0.5

In [4]:
# Implementing the same thing using numpy

np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [5]:
np.mean(np.abs(y_predicted-y_true))

0.5

In [6]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

In [7]:
mae_np(y_predicted, y_true)

0.5

In [8]:
# Implemeting log loss or binary cross entropy

In [10]:
np.log([0.000000000000032])

array([-31.07304049])

In [11]:
# Now in the log function we are subtracting the predicted value from 1 (refer eqn)
# So if the value predicted is 1, it causes a problem of log(0)
# So we are replacing the predicted 1 values with values very close to 1 and same for 0

epsilon = epsilon = 1e-15

In [12]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [13]:
1-epsilon

0.999999999999999

In [14]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [15]:
y_predicted_new = np.array(y_predicted_new)

In [16]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [17]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [19]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [20]:
log_loss(y_true, y_predicted)

17.2696280766844