In [1]:
import tensorflow as tf

2023-06-02 21:13:41.135617: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
daily_sales_numbers = [21, 22, -108, 31, -1, 32, 34,31]

tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)
tf_dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [3]:
for sales in tf_dataset:
    print(sales.numpy())

21
22
-108
31
-1
32
34
31


2023-06-02 21:13:56.160580: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32 and shape [8]
	 [[{{node Placeholder/_0}}]]


In [4]:
# Iterate through elements as numpy elements

for sales in tf_dataset.as_numpy_iterator():
    print(sales)

21
22
-108
31
-1
32
34
31


In [5]:
# Iterate through first n elements in tf dataset

for sales in tf_dataset.take(3):
    print(sales.numpy())

21
22
-108


2023-06-02 21:14:38.252378: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32 and shape [8]
	 [[{{node Placeholder/_0}}]]


In [6]:
# Filter sales numbers that are < 0

tf_dataset = tf_dataset.filter(lambda x: x>0)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

21
22
31
32
34
31


2023-06-02 21:14:50.684020: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32 and shape [8]
	 [[{{node Placeholder/_0}}]]


In [7]:
# Convert sales numbers from USA dollars ($) to Indian Rupees (INR) Assuming 1->82 conversation rate

tf_dataset = tf_dataset.map(lambda x: x*82)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

1722
1804
2542
2624
2788
2542


2023-06-02 21:15:26.555885: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32 and shape [8]
	 [[{{node Placeholder/_0}}]]


In [8]:
# Shuffle
# https://stackoverflow.com/questions/53514495/what-does-batch-repeat-and-shuffle-do-with-tensorflow-dataset

tf_dataset = tf_dataset.shuffle(2)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

1804
2542
2624
1722
2788
2542


2023-06-02 21:15:47.819855: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32 and shape [8]
	 [[{{node Placeholder/_0}}]]
2023-06-02 21:15:47.822319: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32 and shape [8]
	 [[{{node Placeholder/_0}}]]


In [9]:
# Batching

for sales_batch in tf_dataset.batch(2):
    print(sales_batch.numpy())

[1804 1722]
[2624 2788]
[2542 2542]


2023-06-02 21:16:05.094126: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32 and shape [8]
	 [[{{node Placeholder/_0}}]]
2023-06-02 21:16:05.095023: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32 and shape [8]
	 [[{{node Placeholder/_0}}]]


In [10]:
# Perform all of the above operations in one shot

tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)

tf_dataset = tf_dataset.filter(lambda x: x>0).map(lambda y: y*72).shuffle(2).batch(2)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

[1512 1584]
[2304 2232]
[2448 2232]


2023-06-02 21:16:18.224895: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32 and shape [8]
	 [[{{node Placeholder/_0}}]]
2023-06-02 21:16:18.225423: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32 and shape [8]
	 [[{{node Placeholder/_0}}]]


In [12]:
# Images

images_ds = tf.data.Dataset.list_files('images/*/*', shuffle=False)

In [13]:
image_count = len(images_ds)
image_count

130

In [14]:
type(images_ds)

tensorflow.python.data.ops.from_tensor_slices_op._TensorSliceDataset

In [15]:
for file in images_ds.take(3):
    print(file.numpy())

b'images/cat/20 Reasons Why Cats Make the Best Pets....jpg'
b'images/cat/7 Foods Your Cat Can_t Eat.jpg'
b'images/cat/A cat appears to have caught the....jpg'


2023-06-02 21:21:27.833034: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype string and shape [130]
	 [[{{node Placeholder/_0}}]]


In [16]:
images_ds = images_ds.shuffle(200)
for file in images_ds.take(3):
    print(file.numpy())

b'images/dog/How to make your dog feel comfortable....jpg'
b'images/dog/First dog Major back at White House....jpg'
b'images/dog/Colitis in Dogs _ VCA Animal Hospital.jpg'


2023-06-02 21:21:47.520275: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype string and shape [130]
	 [[{{node Placeholder/_0}}]]
2023-06-02 21:21:47.520778: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype string and shape [130]
	 [[{{node Placeholder/_0}}]]


In [17]:
class_names = ["cat","dog"]

In [18]:
# tensorflow equivalent of train_test_split

train_size = int(image_count*0.8)
train_ds = images_ds.take(train_size)
test_ds = images_ds.skip(train_size)

In [19]:
def get_label(file_path):
    import os
    parts = tf.strings.split(file_path, os.path.sep)
    return parts[-2] # indexing from backward

In [21]:
get_label("images/dog/20 Reasons Why Cats Make the Best Pets....jpg")

<tf.Tensor: shape=(), dtype=string, numpy=b'dog'>

In [22]:
def process_image(file_path):
    label = get_label(file_path)
    img = tf.io.read_file(file_path) # load the raw data from the file as a string
    img = tf.image.decode_jpeg(img)
    img = tf.image.resize(img, [128, 128])
    return img, label

In [23]:
img, label = process_image("images/cat/20 Reasons Why Cats Make the Best Pets....jpg")
img.numpy()[:2]

array([[[155.      , 186.      , 215.      ],
        [156.      , 187.      , 216.      ],
        [158.      , 189.      , 218.      ],
        [160.0039  , 189.0039  , 219.0039  ],
        [161.0039  , 190.0039  , 220.0039  ],
        [162.      , 191.      , 221.      ],
        [166.      , 193.      , 222.      ],
        [167.      , 194.      , 223.      ],
        [168.      , 195.      , 224.      ],
        [169.      , 196.      , 225.      ],
        [170.      , 197.      , 224.      ],
        [170.0039  , 197.0039  , 224.0039  ],
        [172.      , 199.      , 226.      ],
        [173.0039  , 199.0039  , 224.0039  ],
        [174.0039  , 200.0039  , 225.0039  ],
        [175.0039  , 201.0039  , 226.0039  ],
        [176.      , 202.      , 227.      ],
        [177.0039  , 203.0039  , 228.0039  ],
        [177.0039  , 203.0039  , 228.0039  ],
        [179.0039  , 203.0039  , 227.0039  ],
        [180.0039  , 204.0039  , 228.0039  ],
        [180.0039  , 204.0039  , 2

In [24]:
train_ds = train_ds.map(process_image)
test_ds = test_ds.map(process_image)

In [25]:
for image, label in train_ds.take(1):
    print("****",image)
    print("****",label)

**** tf.Tensor(
[[[162.      163.      157.     ]
  [164.      165.      159.     ]
  [163.      164.      158.     ]
  ...
  [173.      174.      168.     ]
  [175.      176.      170.     ]
  [173.      174.      168.     ]]

 [[161.      162.      156.     ]
  [164.      165.      159.     ]
  [164.      165.      159.     ]
  ...
  [173.      174.      168.     ]
  [174.      175.      169.     ]
  [174.      175.      169.     ]]

 [[163.      164.      158.     ]
  [163.      164.      158.     ]
  [164.      165.      159.     ]
  ...
  [175.      176.      170.     ]
  [174.      175.      169.     ]
  [174.      175.      169.     ]]

 ...

 [[107.1875   81.1875   90.1875 ]
  [ 29.40625  10.40625  14.40625]
  [ 39.59375  19.59375  21.59375]
  ...
  [ 59.59375  73.59375  50.59375]
  [ 57.40625  70.40625  44.40625]
  [ 54.       68.       42.     ]]

 [[ 61.625    35.625    44.625  ]
  [ 48.53125  29.53125  33.53125]
  [ 43.53125  23.53125  25.53125]
  ...
  [ 55.15625  69.15625

2023-06-02 21:25:11.330159: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype string and shape [130]
	 [[{{node Placeholder/_0}}]]
2023-06-02 21:25:11.330665: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype string and shape [130]
	 [[{{node Placeholder/_0}}]]


In [26]:
def scale(image, label):
    return image/255, label

In [27]:
train_ds = train_ds.map(scale)

In [28]:
for image, label in train_ds.take(5):
    print("****Image: ",image.numpy()[0][0])
    print("****Label: ",label.numpy())

****Image:  [0.860769   0.79018074 0.6960631 ]
****Label:  b'dog'
****Image:  [0.08627451 0.08627451 0.08627451]
****Label:  b'dog'
****Image:  [0.1171492  0.15121017 0.16689645]
****Label:  b'cat'
****Image:  [0.6059436  0.5353554  0.45692402]
****Label:  b'dog'
****Image:  [0.3577304 0.6239124 0.4327638]
****Label:  b'dog'


2023-06-02 21:27:56.587243: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype string and shape [130]
	 [[{{node Placeholder/_0}}]]
2023-06-02 21:27:56.588257: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype string and shape [130]
	 [[{{node Placeholder/_0}}]]
